worlds:
    tests:
    - ZRB5JCISV
    new world:
    - FFNDLCS5E
    - YCY0RSVKZ
    - ZF00PTSTW
    - MACM5MPGO
    - EAYMDU9RU
    - 1FK9DE5LS
    - AGVWPW77H
    - 0AFAWP4KP
    copy of new world:
    - QIA5KGFEK
    - MG1QDWD5X
    - ZF00PTSTW
    - QH5VFGZ3M
    scp:
    - QC3VGS3GL
    tes:
    - DFRDGDVS0
    - 3DXVM36MV
    - DJB3AJJO6
    copy of scp3:
    - YCY0RSVKZ
