worlds:
    tests:
    - ZRB5JCISV
    new world:
    - ZF00PTSTW
    - 1FK9DE5LS
    - AGVWPW77H
    - 0AFAWP4KP
    copy of new world:
    - QIA5KGFEK
    - MG1QDWD5X
    - ZF00PTSTW
    - QH5VFGZ3M
    scp:
    - QC3VGS3GL
